// AUTHENTICATION RELATED--
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const UPDATE_ERROR_TEXT = 'UPDATE_ERROR_TEXT';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const GET_USER_DETAILS = 'GET_USER_DATAILS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const GET_USER_ADDITIONAL_DETAILS = 'GET_USER_ADDITIONAL_DETAILS';
export const GET_USER_SUBSCRIPTION_DATA = 'GET_USER_SUBSCRIPTIONS';
export const GET_IS_ADMIN = "GET_IS_ADMIN";
export const GET_USER_CARDS = "GET_USER_CARDS";
export const GET_USER_GIVING_CARDS = "GET_USER_GIVING_CARDS";
export const LOGOUT = 'LOGOUT';


export const GET_BRANDING='GET_BRANDING';
export const GET_REMOTE_MESSAGE='GET_REMOTE_MESSAGE';
export const GET_ISLAUCHEDFROMNOTIFICATION='GET_ISLAUCHEDFROMNOTIFICATION';

export const UPDATE_CAST_URL ='UPDATE_CAST_URL';
export const UPDATE_CAST_CLIENT = 'UPDATE_CAST_CLIENT';


export const SET_EPUB_THEME = 'SET_EPUB_THEME';
export const SET_EPUB_FONTSIZE = 'SET_EPUB_FONTSIZE';
export const SET_EPUB_FONTFACE = 'SET_EPUB_FONTFACE';
export const RESET_EPUB = 'RESET_EPUB';
export const SET_SPLASH = "SET_SPLASH";
export const SET_SPLASH_URL = 'SET_SPLASH_URL';
export const SET_FETCHED = 'SET_FETCHED';
export const SET_LIVE_ENABLED="SET_LIVE_ENABLED";
export const SET_IOSCOMP="SET_IOS_COMP";
export const SET_ACCESS_MODAL_IOS = "Set access modal ios"
export const SET_NOINTERNET_MODAL='SET_NOINTERNET_MODAL'
export const CHANGE_ORG = "CHANGE_ORG";
export const CHANGE_ENV = 'CHANGE_ENV';
export const SET_PUBLISHED_KEY='SET_PUBLISHED_KEY';
export const SET_YEAR_STRING='SET_YEAR_STRING';
export const STORE_DOWNLOADS = "STORE_DOWNLOADS"
export const SET_ALERT = 'SET_ALERT';
export const UPDATE_ISPAYMENTDONE = 'UPDATE_ISPAYMENTDONE';
export const SET_OTP_ITEMS = "SET_OTP_ITESM";
export const SET_IS_PAYMENT_DONE = "IS_PAYMEN_DONE";
export const SET_SUB_PLAN_IDS = 'SET_SUBSCRIPTION_PLAN_IDS';
export const SET_ALL_PLANS_INAPP = 'SET_ALL_PLANS_INAPP';


export const BIBLE_TYPES = {
    SET_SELECTED_BIBLE: "SET_SELECTED_BIBLE",
    SET_SELECTED_ABB: "SET_SELECTED_ABB",
    SET_CURRENT_BOOKNAME: "SET_CURRENT_BOOK_NAME",
    SET_CURRENT_BOOKID: "SET_CURRENT_BOOKID",
    SET_CURRENT_CHAPTER_ID: "SET_CHAPTER_ID",
    SET_ACTIVE_INDEX: "SET_ACTIVE_INDEX",
    SET_ACTIVE_INDEX_CH: "SET_ACTIVE_INDEX_CHAPTER"
}

